### ISSUE TITLE
Where is latest version of FFmpeg?

### ISSUE THREAD

**Issue by 24Lathiya** [bravobit/FFmpeg-Android#101]
Using your library  in my project. in log i found you are using ffmpeg version 3.3.2

> ffmpeg version 3.3.2 Copyright (c) 2000-2017 the FFmpeg developers
> built with gcc 4.9.x (GCC) 20150123 (prerelease)

please update library with latest FFmpeg. it will help many users.

**Comment by Brianvdb** [comment]
You are probably using an other library. This library uses FFmpeg 4.
