### ISSUE TITLE
error: package nl.bravobit.ffmpeg does not exist

### ISSUE THREAD

**Issue by fakefacebook** [bravobit/FFmpeg-Android#103]
I upgraded 
`implementation 'nl.bravobit:android-ffmpeg:1.1.5'` 
to
 `implementation 'nl.bravobit:android-ffmpeg:1.1.6'`

I got this error
> error: package nl.bravobit.ffmpeg does not exist

**Comment by liamcottle** [comment]
I had the same issue, so stuck with `1.1.5` until resolved.

**Comment by rafabets** [comment]
Me too. I had to go back to the previous version.

**Comment by nzackoya** [comment]
1.1.6 has only migration to androidX, nothing more. I believe everyone here are waiting for FFMPEG upgrade than just updating library versions

**Comment by Brianvdb** [comment]
```
dependencies {
    implementation 'nl.bravobit:android-ffmpeg:1.1.7'
}
```

Fixed!

**Comment by fakefacebook** [comment]
@Brianvdb I solve old one Error but got new one error,


> `Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
> 	is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
> 	Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:8:5-58:19 to override.
> `

**I think this error cause of migration to androidX.**

**Comment by Brianvdb** [comment]
Migrate your project to AndroidX, otherwise keep using version `1.1.5`

**Comment by fakefacebook** [comment]
is there a no other changes in FFMPEG Lib exclude AndroidX?
