### ISSUE TITLE
Support OPUS?

### ISSUE THREAD

**Issue by AdityaAnand1** [bravobit/FFmpeg-Android#11]
Were the binaries compiled with `--enable-libopus`? I see `opus` as one of the listed codecs but when doing a simple conversion, say

```
ffmpeg -i "input.mp3" -acodec libopus -strict -2 "output.opus"
```

The ffmpeg process gets stuck after spitting out the input file metadata and the only way to stop it is to kill the process.

Also, do you think it would be possible to release the binary compilation configuration? That way other devs can just fork and add their own binaries with their own preferred configuration, instead of bloating this library.

**Comment by Brianvdb** [comment]
Opus codecs have been added in version 1.1.1

```gradle
dependencies {
    implementation 'nl.bravobit:android-ffmpeg:1.1.1'
}
```

If you want to compile your own version of FFmpeg take a look [here](https://github.com/WritingMinds/ffmpeg-android/) and modify it to your own needs.
