### ISSUE TITLE
[Android] Using existing ffmpeg shared library.

### ISSUE THREAD

**Issue by arosendorff** [bravobit/FFmpeg-Android#125]
**Description**
I have an app that has the [DJI Mobile SDK](https://developer.dji.com/mobile-sdk/documentation/introduction/index.html) added to it. Part of the SDK is a video streaming component, which uses ffmpeg to decode the frames from the drone.

When I unzip my .apk file, in the libs folder there is `libffmpeg.so`, which I assume is from the DJI SDK. Is there a way that I can use that existing ffmpeg instance with this library, without requiring any additional ffmpeg files to be installed as I want to keep my app size down?

I have tried copying and renaming `libffmpeg.so` to just `ffmpeg` and placing it in the app's files directory, but when I run `FFmpeg.getInstance`, I get: `/data/user/0/APPIDENTIFIER/files/ffmpeg[1]: syntax error: '(' unexpected` so I'm not sure if the .so file is compatible at all. But please let me know if there's perhaps something else I can try to get it working!

**Comment by stonyz** [comment]
You can't do it now. As the lib run ffmpeg in a new process; just like you run ffmpeg on linux.

**Comment by arosendorff** [comment]
@stonyz Okay, thank you very much for the info!
