### ISSUE TITLE
where is jni code?

### ISSUE THREAD

**Issue by trycatchx** [bravobit/FFmpeg-Android#139]
Can you upload JNI code to make it more liberalizable?

**Comment by alexcohn** [comment]
There is no JNI code in this project.

**Comment by trycatchx** [comment]
@alexcohn  Or upload C code?

**Comment by alexcohn** [comment]
The whole _raison d'être_ of this project is to wrap all C logic in a prebuilt library, and let an Android developers easily work with **ffmpeg** executable. One important obstacle that this approach removes, is the strict GPL for **ffmpeg**. If you want to interact with **ffmpeg** via JNI, consider a different project, e.g. **[mobile-ffmpeg](https://github.com/tanersener/mobile-ffmpeg)**.
