### ISSUE TITLE
It is recommended to separate arm from x86

### ISSUE THREAD

**Issue by lodgkk** [bravobit/FFmpeg-Android#147]
The project is too big

**Comment by HBiSoft** [comment]
[You do not need x86](https://android.stackexchange.com/a/186348), you can exclude it from your project by adding the following to your app level`build.gradle`:

```java
android {
    ...
    aaptOptions {
        ignoreAssetsPattern "!x86"
    }
}
```

**Comment by lodgkk** [comment]
thanks

**Comment by HBiSoft** [comment]
@lodgkk 
If that answered your question, you can then close the issue.

**Comment by alexcohn** [comment]
You can use [splits](https://developer.android.com/studio/build/configure-apk-splits.html) to generate arm and x86 flavors of your APK.
