### ISSUE TITLE
good. Is it possible to decrease the size of the app, eliminating the libraries that I do not use?

### ISSUE THREAD

**Issue by orlando9006** [bravobit/FFmpeg-Android#15]
I'm making an app and I use your library, by the way, very good job, but I only use two of its libraries libvorbis, libvpx, how could I eliminate the other libraries if it affects its operation since it weighs too much with the whole package, I would appreciate it if you could help me .

**Comment by Brianvdb** [comment]
The other packages shouldn't impact performance. If size is an issue, you can [Reduce APK File Size](https://github.com/bravobit/FFmpeg-Android/wiki/Reduce-APK-File-Size).

If you really want to eleminate other libraries you will have to compile FFmpeg yourself.

**Comment by HitRoxxx** [comment]
I need only libmp3lame and opus and Vorbis. I am also following Writingminds but when linking static build to a So files  Thes error occurs. Any Suggestion will be helpful :-
`jni/videokit/ffmpeg.c:3552: error: undefined reference to 'av_read_frame'
jni/videokit/ffmpeg.c:3657: error: undefined reference to 'av_read_frame'
jni/videokit/ffmpeg.c:705: error: undefined reference to 'av_apply_bitstream_filters'
jni/videokit/ffmpeg.c:763: error: undefined reference to 'av_interleaved_write_frame'
jni/videokit/ffmpeg.c:2457: error: undefined reference to 'av_sdp_create'
jni/videokit/ffmpeg.c:2463: error: undefined reference to 'avio_open2'
jni/videokit/ffmpeg.c:2466: error: undefined reference to 'avio_printf'
jni/videokit/ffmpeg.c:2467: error: undefined reference to 'avio_closep'
jni/videokit/ffmpeg.c:1265: error: undefined reference to 'av_stream_get_end_pts'
jni/videokit/ffmpeg.c:1544: error: undefined reference to 'avio_size'
/home/hitro/ffmpeg-android-master/ffmpeg/libavformat/avio.h:513: error: undefined reference to 'avio_seek'
jni/videokit/ffmpeg.c:1617: error: undefined reference to 'av_stream_get_end_pts'
jni/videokit/ffmpeg.c:1618: error: undefined reference to 'av_stream_get_end_pts'
jni/videokit/ffmpeg.c:1618: error: undefined reference to 'av_stream_get_end_pts'
jni/videokit/ffmpeg.c:1685: error: undefined reference to 'avio_write'
jni/videokit/ffmpeg.c:1687: error: undefined reference to 'avio_flush'
jni/videokit/ffmpeg.c:1690: error: undefined reference to 'avio_closep'
jni/videokit/ffmpeg.c:499: error: undefined reference to 'avio_closep'
jni/videokit/ffmpeg.c:500: error: undefined reference to 'avformat_free_context'
jni/videokit/ffmpeg.c:542: error: undefined reference to 'avformat_close_input'
jni/videokit/ffmpeg.c:576: error: undefined reference to 'avformat_network_deinit'
jni/videokit/ffmpeg.c:2883: error: undefined reference to 'av_codec_get_id'
jni/videokit/ffmpeg.c:2884: error: undefined reference to 'av_codec_get_tag2'
jni/videokit/ffmpeg.c:3247: error: undefined reference to 'avformat_write_header'
jni/videokit/ffmpeg.c:3265: error: undefined reference to 'av_dump_format'
jni/videokit/ffmpeg.c:2341: error: undefined reference to 'av_stream_get_parser'
jni/videokit/ffmpeg.c:2341: error: undefined reference to 'av_stream_get_parser'
jni/videokit/ffmpeg.c:2415: error: undefined reference to 'av_stream_get_parser'
jni/videokit/ffmpeg.c:2415: error: undefined reference to 'av_stream_get_parser'
jni/videokit/ffmpeg.c:4302: error: undefined reference to 'av_register_all'
jni/videokit/ffmpeg.c:4303: error: undefined reference to 'avformat_network_init'
/home/hitro/ffmpeg-android-master/ffmpeg/libavformat/avio.h:513: error: undefined reference to 'avio_seek'
jni/videokit/ffmpeg.c:3705: error: undefined reference to 'av_seek_frame'
jni/videokit/ffmpeg.c:3820: error: undefined reference to 'av_pkt_dump_log2'
jni/videokit/ffmpeg.c:4171: error: undefined reference to 'av_write_trailer'
jni/videokit/ffmpeg_filter.c:187: error: undefined reference to 'avio_open_dyn_buf'
jni/videokit/ffmpeg_filter.c:187: error: undefined reference to 'avio_printf'
jni/videokit/ffmpeg_filter.c:187: error: undefined reference to 'avio_close_dyn_buf'
jni/videokit/ffmpeg_filter.c:190: error: undefined reference to 'avio_open_dyn_buf'
jni/videokit/ffmpeg_filter.c:190: error: undefined reference to 'avio_printf'
jni/videokit/ffmpeg_filter.c:190: error: undefined reference to 'avio_close_dyn_buf'
jni/videokit/ffmpeg_filter.c:193: error: undefined reference to 'avio_open_dyn_buf'
jni/videokit/ffmpeg_filter.c:193: error: undefined reference to 'avio_printf'
jni/videokit/ffmpeg_filter.c:193: error: undefined reference to 'avio_close_dyn_buf'
jni/videokit/ffmpeg_filter.c:137: error: undefined reference to 'avio_open_dyn_buf'
jni/videokit/ffmpeg_filter.c:149: error: undefined reference to 'avio_close_dyn_buf'
jni/videokit/ffmpeg_filter.c:656: error: undefined reference to 'avio_w8'
jni/videokit/ffmpeg_filter.c:947: error: undefined reference to 'avio_w8'
jni/videokit/ffmpeg_filter.c:729: error: undefined reference to 'av_guess_frame_rate'
jni/videokit/ffmpeg_opt.c:3096: error: undefined reference to 'avio_open2'
jni/videokit/ffmpeg_opt.c:1132: error: undefined reference to 'avio_open2'
jni/videokit/ffmpeg_opt.c:1137: error: undefined reference to 'avio_open2'
jni/videokit/ffmpeg_opt.c:1163: error: undefined reference to 'avformat_new_stream'
jni/videokit/ffmpeg_opt.c:1149: error: undefined reference to 'av_guess_codec'
jni/videokit/ffmpeg_opt.c:1110: error: undefined reference to 'avio_w8'
jni/videokit/ffmpeg_opt.c:1109: error: undefined reference to 'avio_r8'
jni/videokit/ffmpeg_opt.c:1111: error: undefined reference to 'avio_w8'
jni/videokit/ffmpeg_opt.c:1218: error: undefined reference to 'avio_closep'
jni/videokit/ffmpeg_opt.c:1330: error: undefined reference to 'avio_open'
jni/videokit/ffmpeg_opt.c:1343: error: undefined reference to 'avio_read'
jni/videokit/ffmpeg_opt.c:1344: error: undefined reference to 'avio_write'
jni/videokit/ffmpeg_opt.c:801: error: undefined reference to 'avio_find_protocol_name'
jni/videokit/ffmpeg_opt.c:802: error: undefined reference to 'avio_check'
jni/videokit/ffmpeg_opt.c:872: error: undefined reference to 'av_find_input_format'
jni/videokit/ffmpeg_opt.c:885: error: undefined reference to 'avformat_alloc_context'
jni/videokit/ffmpeg_opt.c:934: error: undefined reference to 'av_format_set_video_codec'
jni/videokit/ffmpeg_opt.c:936: error: undefined reference to 'av_format_set_audio_codec'
jni/videokit/ffmpeg_opt.c:938: error: undefined reference to 'av_format_set_subtitle_codec'
jni/videokit/ffmpeg_opt.c:940: error: undefined reference to 'av_format_set_data_codec'
jni/videokit/ffmpeg_opt.c:950: error: undefined reference to 'avformat_open_input'
jni/videokit/ffmpeg_opt.c:970: error: undefined reference to 'avformat_find_stream_info'
jni/videokit/ffmpeg_opt.c:974: error: undefined reference to 'avformat_close_input'
jni/videokit/ffmpeg_opt.c:1005: error: undefined reference to 'avformat_seek_file'
jni/videokit/ffmpeg_opt.c:1016: error: undefined reference to 'av_dump_format'
jni/videokit/ffmpeg_opt.c:1054: error: undefined reference to 'avformat_get_class'
jni/videokit/ffmpeg_opt.c:849: error: undefined reference to 'avio_write'
jni/videokit/ffmpeg_opt.c:850: error: undefined reference to 'avio_flush'
jni/videokit/ffmpeg_opt.c:851: error: undefined reference to 'avio_close'
jni/videokit/ffmpeg_opt.c:1943: error: undefined reference to 'avformat_alloc_output_context2'
jni/videokit/ffmpeg_opt.c:1789: error: undefined reference to 'avformat_alloc_context'
jni/videokit/ffmpeg_opt.c:1792: error: undefined reference to 'avformat_open_input'
jni/videokit/ffmpeg_opt.c:1815: error: undefined reference to 'av_stream_get_recommended_encoder_configuration'
jni/videokit/ffmpeg_opt.c:1832: error: undefined reference to 'avformat_close_input'
jni/videokit/ffmpeg_opt.c:2018: error: undefined reference to 'av_guess_codec'
jni/videokit/ffmpeg_opt.c:2020: error: undefined reference to 'avformat_query_codec'
jni/videokit/ffmpeg_opt.c:2040: error: undefined reference to 'av_guess_codec'
jni/videokit/ffmpeg_opt.c:2086: error: undefined reference to 'av_guess_codec'
jni/videokit/ffmpeg_opt.c:2178: error: undefined reference to 'avio_size'
jni/videokit/ffmpeg_opt.c:2188: error: undefined reference to 'avio_read'
jni/videokit/ffmpeg_opt.c:2214: error: undefined reference to 'av_dump_format'
jni/videokit/ffmpeg_opt.c:2233: error: undefined reference to 'avformat_get_class'
jni/videokit/ffmpeg_opt.c:2274: error: undefined reference to 'av_filename_number_test'
jni/videokit/ffmpeg_opt.c:2297: error: undefined reference to 'av_filename_number_test'
jni/videokit/ffmpeg_opt.c:2390: error: undefined reference to 'av_new_program'
jni/videokit/ffmpeg_opt.c:2417: error: undefined reference to 'av_program_add_stream_index'
jni/videokit/ffmpeg_opt.c:2970: error: undefined reference to 'avformat_get_class'
jni/videokit/cmdutils.c:1255: error: undefined reference to 'av_oformat_next'
jni/videokit/cmdutils.c:1266: error: undefined reference to 'av_iformat_next'
jni/videokit/cmdutils.c:1080: error: undefined reference to 'avformat_version'
jni/videokit/cmdutils.c:1080: error: undefined reference to 'avformat_configuration'
jni/videokit/cmdutils.c:529: error: undefined reference to 'avformat_get_class'
jni/videokit/cmdutils.c:1581: error: undefined reference to 'avio_enum_protocols'
jni/videokit/cmdutils.c:1584: error: undefined reference to 'avio_enum_protocols'
jni/videokit/cmdutils.c:1757: error: undefined reference to 'av_find_input_format'
jni/videokit/cmdutils.c:1776: error: undefined reference to 'av_guess_format'
jni/videokit/cmdutils.c:1959: error: undefined reference to 'avformat_match_stream_specifier'
jni/videokit/cmdutils.c:2064: error: undefined reference to 'av_stream_get_side_data'
libavfilter/f_metadata.c:187: error: undefined reference to 'avio_write'
libavfilter/f_metadata.c:252: error: undefined reference to 'avio_open'
libavfilter/f_metadata.c:254: error: undefined reference to 'avio_open'
libavfilter/lavfutils.c:39: error: undefined reference to 'av_register_all'
libavfilter/lavfutils.c:41: error: undefined reference to 'av_find_input_format'
libavfilter/lavfutils.c:42: error: undefined reference to 'avformat_open_input'
libavfilter/lavfutils.c:48: error: undefined reference to 'avformat_find_stream_info'
libavfilter/lavfutils.c:73: error: undefined reference to 'av_read_frame'
libavfilter/lavfutils.c:100: error: undefined reference to 'avformat_close_input'
libavfilter/src_movie.c:621: error: undefined reference to 'av_seek_frame'
libavfilter/src_movie.c:440: error: undefined reference to 'av_seek_frame'
libavfilter/src_movie.c:492: error: undefined reference to 'av_read_frame'
libavfilter/src_movie.c:238: error: undefined reference to 'av_register_all'
libavfilter/src_movie.c:241: error: undefined reference to 'av_find_input_format'
libavfilter/src_movie.c:244: error: undefined reference to 'avformat_open_input'
libavfilter/src_movie.c:249: error: undefined reference to 'avformat_find_stream_info'
libavfilter/src_movie.c:265: error: undefined reference to 'av_seek_frame'
libavfilter/src_movie.c:108: error: undefined reference to 'av_find_best_stream'
libavfilter/src_movie.c:117: error: undefined reference to 'avformat_match_stream_specifier'
libavcodec/libvorbisenc.c:98: error: undefined reference to 'vorbis_encode_setup_vbr'
libavcodec/libvorbisenc.c:107: error: undefined reference to 'vorbis_encode_setup_managed'
libavcodec/libvorbisenc.c:114: error: undefined reference to 'vorbis_encode_ctl'
libavcodec/libvorbisenc.c:121: error: undefined reference to 'vorbis_encode_ctl'
libavcodec/libvorbisenc.c:127: error: undefined reference to 'vorbis_encode_ctl'
libavcodec/libvorbisenc.c:160: error: undefined reference to 'vorbis_encode_setup_init'
/home/hitro/ffmpeg-android-master/libmp3lame/lib/libvorbis.a(block.o):block.c:function vorbis_block_init: error: undefined reference to 'oggpack_writeinit'
/home/hitro/ffmpeg-android-master/libmp3lame/lib/libvorbis.a(block.o):block.c:function vorbis_block_init: error: undefined reference to 'oggpack_writeinit'
/home/hitro/ffmpeg-android-master/libmp3lame/lib/libvorbis.a(block.o):block.c:function vorbis_block_clear: error: undefined reference to 'oggpack_writeclear'
/home/hitro/ffmpeg-android-master/libmp3lame/lib/libvorbis.a(analysis.o):analysis.c:function vorbis_analysis: error: undefined reference to 'oggpack_reset'
/home/hitro/ffmpeg-android-master/libmp3lame/lib/libvorbis.a(analysis.o):analysis.c:function vorbis_analysis: error: undefined reference to 'oggpack_get_buffer'
/home/hitro/ffmpeg-android-master/libmp3lame/lib/libvorbis.a(analysis.o):analysis.c:function vorbis_analysis: error: undefined reference to 'oggpack_bytes'
/home/hitro/ffmpeg-android-master/libmp3lame/lib/libvorbis.a(synthesis.o):synthesis.c:function vorbis_synthesis: error: undefined reference to 'oggpack_readinit'
/home/hitro/ffmpeg-android-master/libmp3lame/lib/libvorbis.a(synthesis.o):synthesis.c:function vorbis_synthesis: error: undefined reference to 'oggpack_read'
/home/hitro/ffmpeg-android-master/libmp3lame/lib/libvorbis.a(synthesis.o):synthesis.c:function vorbis_synthesis: error: undefined reference to 'oggpack_read'
/home/hitro/ffmpeg-android-master/libmp3lame/lib/libvorbis.a(synthesis.o):synthesis.c:function vorbis_synthesis: error: undefined reference to 'oggpack_read'
/home/hitro/ffmpeg-android-master/libmp3lame/lib/libvorbis.a(synthesis.o):synthesis.c:function vorbis_synthesis: error: undefined reference to 'oggpack_read'
/home/hitro/ffmpeg-android-master/libmp3lame/lib/libvorbis.a(synthesis.o):synthesis.c:function vorbis_synthesis_trackonly: error: undefined reference to 'oggpack_readinit'
/home/hitro/ffmpeg-android-master/libmp3lame/lib/libvorbis.a(synthesis.o):synthesis.c:function vorbis_packet_blocksize: error: undefined reference to 'oggpack_readinit'
/home/hitro/ffmpeg-android-master/libmp3lame/lib/libvorbis.a(info.o):info.c:function _vorbis_pack_comment: error: undefined reference to 'oggpack_write'
/home/hitro/ffmpeg-android-master/libmp3lame/lib/libvorbis.a(info.o):info.c:function _vorbis_pack_comment: error: undefined reference to 'oggpack_write'
/home/hitro/ffmpeg-android-master/libmp3lame/lib/libvorbis.a(info.o):info.c:function _vorbis_pack_comment: error: undefined reference to 'oggpack_write'
/home/hitro/ffmpeg-android-master/libmp3lame/lib/libvorbis.a(info.o):info.c:function _vorbis_pack_comment: error: undefined reference to 'oggpack_write'
/home/hitro/ffmpeg-android-master/libmp3lame/lib/libvorbis.a(info.o):info.c:function vorbis_synthesis_idheader: error: undefined reference to 'oggpack_readinit'
/home/hitro/ffmpeg-android-master/libmp3lame/lib/libvorbis.a(info.o):info.c:function vorbis_synthesis_headerin: error: undefined reference to 'oggpack_bytes'
/home/hitro/ffmpeg-android-master/libmp3lame/lib/libvorbis.a(info.o):info.c:function vorbis_synthesis_headerin: error: undefined reference to 'oggpack_bytes'
/home/hitro/ffmpeg-android-master/libmp3lame/lib/libvorbis.a(info.o):info.c:function vorbis_commentheader_out: error: undefined reference to 'oggpack_writeinit'
/home/hitro/ffmpeg-android-master/libmp3lame/lib/libvorbis.a(info.o):info.c:function vorbis_commentheader_out: error: undefined reference to 'oggpack_bytes'
/home/hitro/ffmpeg-android-master/libmp3lame/lib/libvorbis.a(info.o):info.c:function vorbis_commentheader_out: error: undefined reference to 'oggpack_writeclear'
/home/hitro/ffmpeg-android-master/libmp3lame/lib/libvorbis.a(info.o):info.c:function vorbis_commentheader_out: error: undefined reference to 'oggpack_writeclear'
/home/hitro/ffmpeg-android-master/libmp3lame/lib/libvorbis.a(info.o):info.c:function vorbis_analysis_headerout: error: undefined reference to 'oggpack_writeinit'
/home/hitro/ffmpeg-android-master/libmp3lame/lib/libvorbis.a(info.o):info.c:function vorbis_analysis_headerout: error: undefined reference to 'oggpack_reset'
/home/hitro/ffmpeg-android-master/libmp3lame/lib/libvorbis.a(info.o):info.c:function vorbis_analysis_headerout: error: undefined reference to 'oggpack_reset'
/home/hitro/ffmpeg-android-master/libmp3lame/lib/libvorbis.a(info.o):info.c:function vorbis_analysis_headerout: error: undefined reference to 'oggpack_writeclear'
/home/hitro/ffmpeg-android-master/libmp3lame/lib/libvorbis.a(codebook.o):codebook.c:function vorbis_book_decode: error: undefined reference to 'oggpack_look'
/home/hitro/ffmpeg-android-master/libmp3lame/lib/libvorbis.a(codebook.o):codebook.c:function vorbis_book_decode: error: undefined reference to 'oggpack_look'
/home/hitro/ffmpeg-android-master/libmp3lame/lib/libvorbis.a(codebook.o):codebook.c:function vorbis_book_decode: error: undefined reference to 'oggpack_adv'
/home/hitro/ffmpeg-android-master/libmp3lame/lib/libvorbis.a(codebook.o):codebook.c:function vorbis_book_decode: error: undefined reference to 'oggpack_adv'
/home/hitro/ffmpeg-android-master/libmp3lame/lib/libvorbis.a(codebook.o):codebook.c:function vorbis_book_decode: error: undefined reference to 'oggpack_adv'
/home/hitro/ffmpeg-android-master/libmp3lame/lib/libvorbis.a(codebook.o):codebook.c:function vorbis_book_decodevs_add: error: undefined reference to 'oggpack_look'
/home/hitro/ffmpeg-android-master/libmp3lame/lib/libvorbis.a(codebook.o):codebook.c:function vorbis_book_decodevs_add: error: undefined reference to 'oggpack_look'
/home/hitro/ffmpeg-android-master/libmp3lame/lib/libvorbis.a(codebook.o):codebook.c:function vorbis_book_decodevs_add: error: undefined reference to 'oggpack_adv'
/home/hitro/ffmpeg-android-master/libmp3lame/lib/libvorbis.a(bitrate.o):bitrate.c:function vorbis_bitrate_addblock: error: undefined reference to 'oggpack_writetrunc'
/home/hitro/ffmpeg-android-master/libmp3lame/lib/libvorbis.a(bitrate.o):bitrate.c:function vorbis_bitrate_flushpacket: error: undefined reference to 'oggpack_get_buffer'
collect2: error: ld returned 1 exit status
make: *** [obj/local/armeabi-v7a/libvideokit.so] Error 1

Process finished with exit code 2
`

**Comment by Brianvdb** [comment]
Please post that issue on the writingminds issue tracker. This is not the place where these kind of questions belong.

**Comment by orlando9006** [comment]
could you guide me how to compile ffmpeg, greetings
