### ISSUE TITLE
how to generate the file in your project

### ISSUE THREAD

**Issue by frinda** [bravobit/FFmpeg-Android#16]
well ,thank you very much, how to generate the file in your project(android-ffmepg) below the  arm or x86 using the FFmpeg 3.4.1. I want to generate file using FFmpeg 3.3.6.but I don't know how to generate ,I  only can produce the file ffmpeg.so file .please help me .thank you ,thank you very much

**Comment by Brianvdb** [comment]
You can probably rename the file to ffmpeg and use it.

However, this is not an issue which relates to this repository.
