### ISSUE TITLE
Failed to resolve implementation

### ISSUE THREAD

**Issue by CodePlayMX2** [bravobit/FFmpeg-Android#18]
Hi, i am trying to use ffmpeg in my android studio project,
but it's get failed on resolving the depency 'nl.bravobit:android-ffmpeg:1.1.1'
What can i do ?

**Comment by Brianvdb** [comment]
The library is hosted on jCenter.

Project gradle
```gradle
allprojects {
    repositories {
        jcenter()
    }
}
```
