### ISSUE TITLE
Large library size due to ffprobe

### ISSUE THREAD

**Issue by korolevdev** [bravobit/FFmpeg-Android#20]
https://github.com/WritingMinds/ffmpeg-android-java does not contain ffprobe and because of this it weighs not so much. Is there a need for ffprobe?

**Comment by Brianvdb** [comment]
You can exclude FFprobe. It is not required.

[https://github.com/bravobit/FFmpeg-Android/wiki/Reduce-APK-File-Size#exclude-ffprobe](https://github.com/bravobit/FFmpeg-Android/wiki/Reduce-APK-File-Size#exclude-ffprobe)
