### ISSUE TITLE
How to exclude both ffprobe and arm/ffmpeg?

### ISSUE THREAD

**Issue by AdityaAnand1** [bravobit/FFmpeg-Android#21]
This would cut my debug build apk sizes in half. I don't use ffprobe at all, so I don't want it in the debug builds and I dev mostly on emulator so no point in shipping arm binary.

I've tried the following

                ignoreAssetsPattern "!ffprobe:!arm"

And it doesn't work, but 

                ignoreAssetsPattern "!ffprobe"

and 

                ignoreAssetsPattern "!arm"

do work individually. But what I want is only ffmpeg in x86, any ideas?

**Comment by Brianvdb** [comment]
```gradle
aaptOptions {
     ignoreAssetsPattern "!ffprobe:!arm:"
}
```

This seems to work fine for me. When I build an APK the size is just 10mb.

**Comment by AdityaAnand1** [comment]
Omg, I tried literally every permutation I could think of except adding a colon at the end. There's literally no syntax/documentation for this anywhere.

-_-

Thank you.
