### ISSUE TITLE
config file

### ISSUE THREAD

**Issue by mehdishz11** [bravobit/FFmpeg-Android#23]
I search too much to find a build bash for making ffmpeg prebuilt but every time I want to use to final result I got so many errors like :
`error: only position independent executables (PIE) are supported.`

so could you please give us your configuration build bash .
I try to use from [](https://github.com/WritingMinds/ffmpeg-android) but I couldn't

especially thanks.

**Comment by Brianvdb** [comment]
Checkout this project: [https://github.com/WritingMinds/ffmpeg-android](https://github.com/WritingMinds/ffmpeg-android)
