### ISSUE TITLE
Argument FFcommandExecuteAsyncTask for isCommandRunning()

### ISSUE THREAD

**Issue by adriandleon** [bravobit/FFmpeg-Android#28]
I'm using the latest version 1.1.2 and I need to check if ffmpeg is already running a command, isCommandRunning() needs an argument of type FFcommandExecuteAsyncTask but FFmpeg.execute() returns an object of type FFTask.

In previous version (1.0.4) isCommandRunning() didn't have any argument.

Same with the killRunningProcesses() method.

**Comment by adriandleon** [comment]
Any comment on that?

I am in a middle of a project and I need to know if ffmpeg is running or not, so I'm going to rollback to an earlier version.

What is the latest version where isCommandRunning() works?

**Comment by Brianvdb** [comment]
This is fixed in version `1.1.3`. You can call `isCommandRunning()` directly on the FFtask that is returned.
