### ISSUE TITLE
May you build ffmpeg with libvorbis enabled?

### ISSUE THREAD

**Issue by liuatgit** [bravobit/FFmpeg-Android#3]
May you build ffmpeg with libvorbis enabled? thx!

**Comment by Brianvdb** [comment]
libvorbis support was added in bab97eadc1d91c54e21a943b24f247edcf97ecb3

Use the new version
```gradle
dependencies {
    implementation 'nl.bravobit:android-ffmpeg:1.0.6'
}
```

**Comment by liuatgit** [comment]
Just test the new version on OGG file and it works great!
