### ISSUE TITLE
Upgrade to FFmpeg 4.0

### ISSUE THREAD

**Issue by AdityaAnand1** [bravobit/FFmpeg-Android#31]
https://ffmpeg.org/index.html#pr4.0

:tada:

**Comment by liuatgit** [comment]
I'm waiting for 4.0 too.

**Comment by NiekAkerboom** [comment]
@AdityaAnand1 @liuatgit You guys can build it yourself, which I highly recommend. Most FFmpeg binaries you find online have modules enabled that you might never use which will increase the size of it immensely.

**Comment by Brianvdb** [comment]
@AdityaAnand1 @liuatgit 

Good news! FFmpeg 4.0 is now supported by this library since version 1.1.4

```gradle
dependencies {
    implementation 'nl.bravobit:android-ffmpeg:1.1.4'
}
```

**Comment by nzackoya** [comment]
It is still 3.0.1
