### ISSUE TITLE
Building FFmpeg executable from source

### ISSUE THREAD

**Issue by mirrajabi** [bravobit/FFmpeg-Android#33]
Hi,
I can see that you've fixed the `text relocations` issue on x86 devices. but I want to know how you fixed this and can you share the steps or commands you used for this fix?

**Comment by Brianvdb** [comment]
You should be able to build it for x86 with the --disable-asm flag.

**Comment by bolds07** [comment]
are you using this flag on every single dependency you build or just on ffmpeg...
because i`m already using it and still get the error
