### ISSUE TITLE
Removing audio from video

### ISSUE THREAD

**Issue by ritesh94** [bravobit/FFmpeg-Android#35]
@Brianvdb 
**Gradle**: `implementation 'nl.bravobit:android-ffmpeg:1.1.5'`

I get following in **logs** : 
`[mp4 @ 0xb8e5d550] Non-monotonous DTS in output stream 0:0; previous: 19, current: 0; changing to 20. This may result in incorrect timestamps in the output file.`

When I try to remove the audio from video using the **command**: 
`-y -i /storage/emulated/0/video_trimmed.mp4 -an -vcodec copy /storage/emulated/0/no_audio.mp4` ,

Also, the video has a little glitch between starting 0 to 2 seconds !!

**Comment by Brianvdb** [comment]
This is not an issue related to this library.
