### ISSUE TITLE
Support APK ABI Splits

### ISSUE THREAD

**Issue by jonasbark** [bravobit/FFmpeg-Android#36]
Thanks for the library, it works really well!

According to what I understand abi splits for APKs (https://developer.android.com/studio/build/configure-apk-splits) is not supported for this library as the binaries are included in the assets directory. Can you think of any way to support apk splits?

**Comment by Brianvdb** [comment]
Yes you can still reduce the APK size. You can read about it in the [wiki](https://github.com/bravobit/FFmpeg-Android/wiki/Reduce-APK-File-Size).

**Comment by jonasbark** [comment]
Damn, sorry I missed that. Maybe it'll be a good idea to reference this in the Readme.
