### ISSUE TITLE
Why do you write wrong FFMPEG version in readme file?

### ISSUE THREAD

**Issue by nzackoya** [bravobit/FFmpeg-Android#40]
The real version of the FFMPEG is 3.0.1
ffmpeg version n3.0.1 Copyright (c) 2000-2016 the FFmpeg developers.
Would be better if you update it.

**Comment by Brianvdb** [comment]
The README is correct.

**Comment by nzackoya** [comment]
I tried to downgrade or update but the FFMPEG version is still 3.0.1.
