### ISSUE TITLE
Uses the latest FFmpeg release n4.0-39-gda39990

### ISSUE THREAD

**Issue by nzackoya** [bravobit/FFmpeg-Android#41]
I updated to this library after using ffmpeg-android-java, but the version of the ffmpeg is still 3.0.1, and not 4.0 or even 3.4. Is there anything I need to setup?

**Comment by Sub6Resources** [comment]
Are you sure you are calling this library and not ffmpeg-android-java?

**Comment by Brianvdb** [comment]
Duplicate of: #40

The library is using FFmpeg 4.0.

**Comment by nzackoya** [comment]
@Sub6Resources I removed ffmpeg-android-java, cleaned the project, rebuilt, and run again. But ssill it is 3.0.1. Should I do anything else?

**Comment by Sub6Resources** [comment]
@nzackoya Try uninstalling or clearing data for your app on the emulator/device and running again. Perhaps the old binary is still there.
