### ISSUE TITLE
Remove FFprobe, to reduce APK?

### ISSUE THREAD

**Issue by formatBCE** [bravobit/FFmpeg-Android#43]
Could you please give some highlights of removing FFprobe? It significantly raises APK size, and i don't need it in my project. Should i fork it, or maybe, you have separate build?

**Comment by Brianvdb** [comment]
Duplicate of #20 

You can find this in the WIKI: [https://github.com/bravobit/FFmpeg-Android/wiki/Reduce-APK-File-Size](https://github.com/bravobit/FFmpeg-Android/wiki/Reduce-APK-File-Size)
