### ISSUE TITLE
Is there any way to improve process time?

### ISSUE THREAD

**Issue by huunhan18pro** [bravobit/FFmpeg-Android#48]
Hi @Brianvdb ,  How can I improve process time?
 - I execute this command to join videos and add overlay, speed about 0.6. How can I improve it?
` String overlay = "-i " + video1 + " -i " + video2 + " -i " + exclusivePhoto + " -filter_complex [0:v][0:a][1:v][1:a]concat=n=2:v=1:a=1[vv][a];[vv][2:v]overlay=0:0[v] -map [v] -map [a] -b:v 3650000";`

**Comment by Brianvdb** [comment]
The flag `-preset ultrafast` should improve it.
