### ISSUE TITLE
May you build ffmpeg with libvpx enabled? 

### ISSUE THREAD

**Issue by orlando9006** [bravobit/FFmpeg-Android#5]
would be very grateful if you added the above-mentioned libraries to your project, since I need to convert a gif to webm, thank you very much excellent project

**Comment by Brianvdb** [comment]
Libvorbes was added in the latest version. I will check libvpx later.

**Comment by orlando9006** [comment]
thanks for your help, since I enabled libvosid, I hope with ancias that I can enable libvpx, I would appreciate it very much, it is very necessary, thanks for your help.

**Comment by vxhviet** [comment]
Hi @Brianvdb 
If it's prossible, could you start a wiki page on how to build the ffmpeg? With that people can customize the build to their requirements and in case, you're too busy, someone else can still keep this repo updated. 

Thank you very much for your effort.

**Comment by Brianvdb** [comment]
Libvpx has now been added in version 1.0.9

This means that webm encoder/decoder is now supported.

```gradle
dependencies {
    implementation 'nl.bravobit:android-ffmpeg:1.0.9'
}
```
