### ISSUE TITLE
CANNOT LINK EXECUTABLE ffmpeg: has text relocations

### ISSUE THREAD

**Issue by HBiSoft** [bravobit/FFmpeg-Android#51]
I still get `CANNOT LINK EXECUTABLE ffmpeg: has text relocations` running Nexus 5X (Android 8.1.0, API 27, x86).

Could this be because I'm testing on a emulator?

**Comment by HBiSoft** [comment]
This issue was related to the emulator I was using.

**Comment by MustaphaGhlissi** [comment]
@HBiSoft did you resolve this problem ? 


I have the same error , any solution please !! 

Regards

**Comment by HBiSoft** [comment]
I posted above what my issue was...

**Comment by HBiSoft** [comment]
@MustaphaGhlissi Can you tell me, why exactly, you downvoted my comment? You asked me what my issue was and I told you. You could have asked me another question instead of down voting a comment.

**Comment by blockchainGuru1018** [comment]
I am getting same issue
