### ISSUE TITLE
Integration with MLT melt framework

### ISSUE THREAD

**Issue by mwshubham** [bravobit/FFmpeg-Android#52]
I recently came to know that MLT work out of the box when applying transitions. In my current requirement, I was able to develop a feature via FFMpeg. However, I am a bit stuck at complex transition. Does this bundle support MLT? Is MLT should be used separately instead of using FFMpeg? How to integrate MLT with Android framework?

**Comment by Brianvdb** [comment]
This is not something we support, and as you asked [here](https://github.com/mltframework/mlt/issues/355) there is no documentation on how to compile this.

Maybe something for the future.
