### ISSUE TITLE
how could i change the path of ffmpeg ?

### ISSUE THREAD

**Issue by mohamedmorsi95** [bravobit/FFmpeg-Android#55]
how could i change the path of ffmpeg because there is some different storage architecture with some  devices that is why i had this error 

java.io.IOException: Cannot run program "/data/user/0/(package.name)/files/ffmpeg": error=2, No such file or directory

the path of this storage is "/storage/emulated/0/package.name/ffmpeg/"

**Comment by Brianvdb** [comment]
Are you excluding FFmpeg for specific architectures? Please provide some more details.

**Comment by mwshubham** [comment]
Happen with me when i used` ignoreAssetsPattern "!ffprobe:!x86:"` thus ignored ffmpeg for x86 architecture

**Comment by prolok** [comment]
I also have the same issue. Previously I used https://github.com/WritingMinds/ffmpeg-android-java and changed to use this by updating the build.gradle file. But on both android 7 and 8 I also got `java.io.IOException: Cannot run program "/data/user/0/package.name/files/ffmpeg": error=2, No such file or directory`. Any idea on how can I handle it?

**Comment by prolok** [comment]
@Brianvdb The ffmpeg (and also ffprobe) file is never copied from assets to the file system in the project. Looks like this project is not supposed to be used alone, or something else is missing in the latest version?

**Comment by anilson** [comment]
`FFmpeg.getInstance(this).isSupported()` will perform the installation.
See lines 42-77 in FFmpeg.java

**Comment by Brianvdb** [comment]
@anilson is right.

```
FFmpeg.getInstance(this).isSupported()
```

Will fix the issue.
