### ISSUE TITLE
ffmpeg on android on a video http

### ISSUE THREAD

**Issue by Angelk90** [bravobit/FFmpeg-Android#56]
@Bravobit , @Brianvdb : 
Hi, using this module it would be possible to create such a thing, from an http video. 
![](https://www.bogotobogo.com/FFMpeg/images/scenechange/Yosemite_preview.png)

**Comment by mwshubham** [comment]
protocol HTTP is not supported AFAIK however you can create the video if you have in your local storage

**Comment by HBiSoft** [comment]
FFmpeg supports streaming (https://trac.ffmpeg.org/wiki/StreamingGuide) but your question is unclear and not related to the library.

**Comment by Brianvdb** [comment]
`http` is supported, `https` not (yet).
