### ISSUE TITLE
ffmpeg stream rtsp copy to .mp4

### ISSUE THREAD

**Issue by rauldam** [bravobit/FFmpeg-Android#66]
Hi all, i'm trying to use ffmpeg android to choose a rtsp stream and copy into a internal storage in .mp4,
i have a command fffmpeg -i rtsp://192.168.1.108:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif -tune zerolatency -vcodec libx264 -t 12:00:00 -pix_fmt + -c:v copy -c:a libfdk_aac -vcodec copy {RUTA} in my RPI and it is working perfectly, but when i put this command in Android only have this:
09-24 14:12:31.230 24858-24858/com.goodidea.ffmpeg D/FFmpeg: Build.CPU_ABI : armeabi-v7a
09-24 14:12:31.233 24858-24858/com.goodidea.ffmpeg D/FFmpeg: ffmpeg is ready!
09-24 14:12:31.264 24858-24900/com.goodidea.ffmpeg D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: false
09-24 14:12:31.267 24858-24897/com.goodidea.ffmpeg D/FFmpeg: Running publishing updates method
09-24 14:12:31.516 24858-24858/com.goodidea.ffmpeg D/PROGRES: ffmpeg version n4.0-39-gda39990 Copyright (c) 2000-2018 the FFmpeg developers
09-24 14:12:31.516 24858-24858/com.goodidea.ffmpeg D/PROGRES:   built with gcc 4.9.x (GCC) 20150123 (prerelease)
09-24 14:12:31.516 24858-24858/com.goodidea.ffmpeg D/PROGRES:   configuration: --target-os=linux --cross-prefix=/root/bravobit/ffmpeg-android/toolchain-android/bin/arm-linux-androideabi- --arch=arm --cpu=cortex-a8 --enable-runtime-cpudetect --sysroot=/root/bravobit/ffmpeg-android/toolchain-android/sysroot --enable-pic --enable-libx264 --enable-ffprobe --enable-libopus --enable-libvorbis --enable-libfdk-aac --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-fontconfig --enable-libvpx --enable-libass --enable-yasm --enable-pthreads --disable-debug --enable-version3 --enable-hardcoded-tables --disable-ffplay --disable-linux-perf --disable-doc --disable-shared --enable-static --enable-runtime-cpudetect --enable-nonfree --enable-network --enable-avresample --enable-avformat --enable-avcodec --enable-indev=lavfi --enable-hwaccels --enable-ffmpeg --enable-zlib --enable-gpl --enable-small --enable-nonfree --pkg-config=pkg-config --pkg-config-flags=--static --prefix=/root/bravobit/ffmpeg-android/build/armeabi-v7a --extra-cflags='-I/root/bravobit/ffmpeg-android/toolchain-android/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fno-strict-overflow -fstack-protector-all' --extra-ldflags='-L/root/bravobit/ffmpeg-android/toolchain-android/lib -Wl,-z,relro -Wl,-z,now -pie' --extra-cxxflags=
09-24 14:12:31.516 24858-24858/com.goodidea.ffmpeg D/PROGRES:   libavutil      56. 14.100 / 56. 14.100
09-24 14:12:31.516 24858-24858/com.goodidea.ffmpeg D/PROGRES:   libavcodec     58. 18.100 / 58. 18.100
09-24 14:12:31.516 24858-24858/com.goodidea.ffmpeg D/PROGRES:   libavformat    58. 12.100 / 58. 12.100
09-24 14:12:31.516 24858-24858/com.goodidea.ffmpeg D/PROGRES:   libavdevice    58.  3.100 / 58.  3.100
09-24 14:12:31.516 24858-24858/com.goodidea.ffmpeg D/PROGRES:   libavfilter     7. 16.100 /  7. 16.100
09-24 14:12:31.516 24858-24858/com.goodidea.ffmpeg D/PROGRES:   libavresample   4.  0.  0 /  4.  0.  0
09-24 14:12:31.517 24858-24858/com.goodidea.ffmpeg D/PROGRES:   libswscale      5.  1.100 /  5.  1.100
09-24 14:12:31.517 24858-24858/com.goodidea.ffmpeg D/PROGRES:   libswresample   3.  1.100 /  3.  1.100
09-24 14:12:31.517 24858-24858/com.goodidea.ffmpeg D/PROGRES:   libpostproc    55.  1.100 / 55.  1.100
09-24 14:12:31.517 24858-24858/com.goodidea.ffmpeg D/PROGRES: Output #0, mp4, to 'ffmpeg -i rtsp://192.168.1.108:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif -tune zerolatency -vcodec libx264 -t 12:00:00 -pix_fmt + -c:v copy -c:a libfdk_aac -vcodec copy /storage/emulated/0abc.mp4':
09-24 14:12:31.517 24858-24858/com.goodidea.ffmpeg D/PROGRES: Output file #0 does not contain any stream
09-24 14:12:31.517 24858-24858/com.goodidea.ffmpeg D/ERROR: ffmpeg version n4.0-39-gda39990 Copyright (c) 2000-2018 the FFmpeg developers
                                                              built with gcc 4.9.x (GCC) 20150123 (prerelease)
                                                              configuration: --target-os=linux --cross-prefix=/root/bravobit/ffmpeg-android/toolchain-android/bin/arm-linux-androideabi- --arch=arm --cpu=cortex-a8 --enable-runtime-cpudetect --sysroot=/root/bravobit/ffmpeg-android/toolchain-android/sysroot --enable-pic --enable-libx264 --enable-ffprobe --enable-libopus --enable-libvorbis --enable-libfdk-aac --enable-libfreetype --enable-libfribidi --enable-libmp3lame --enable-fontconfig --enable-libvpx --enable-libass --enable-yasm --enable-pthreads --disable-debug --enable-version3 --enable-hardcoded-tables --disable-ffplay --disable-linux-perf --disable-doc --disable-shared --enable-static --enable-runtime-cpudetect --enable-nonfree --enable-network --enable-avresample --enable-avformat --enable-avcodec --enable-indev=lavfi --enable-hwaccels --enable-ffmpeg --enable-zlib --enable-gpl --enable-small --enable-nonfree --pkg-config=pkg-config --pkg-config-flags=--static --prefix=/root/bravobit/ffmpeg-android/build/armeabi-v7a --extra-cflags='-I/root/bravobit/ffmpeg-android/toolchain-android/include -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -fno-strict-overflow -fstack-protector-all' --extra-ldflags='-L/root/bravobit/ffmpeg-android/toolchain-android/lib -Wl,-z,relro -Wl,-z,now -pie' --extra-cxxflags=
                                                              libavutil      56. 14.100 / 56. 14.100
                                                              libavcodec     58. 18.100 / 58. 18.100
                                                              libavformat    58. 12.100 / 58. 12.100
                                                              libavdevice    58.  3.100 / 58.  3.100
                                                              libavfilter     7. 16.100 /  7. 16.100
                                                              libavresample   4.  0.  0 /  4.  0.  0
                                                              libswscale      5.  1.100 /  5.  1.100
                                                              libswresample   3.  1.100 /  3.  1.100
                                                              libpostproc    55.  1.100 / 55.  1.100
                                                            Output #0, mp4, to 'ffmpeg -i rtsp://192.168.1.108:554/cam/realmonitor?channel=1&subtype=0&unicast=true&proto=Onvif -tune zerolatency -vcodec libx264 -t 12:00:00 -pix_fmt + -c:v copy -c:a libfdk_aac -vcodec copy /storage/emulated/0abc.mp4':Output file #0 does not contain any stream

Thx

**Comment by Brianvdb** [comment]
Did you add the internet permission in the AndroidManifest? And are you connected with WiFi on your Android device?

**Comment by rauldam** [comment]
The issue has been resolved, the problem was in the command array.

**Comment by jambestwick** [comment]
@rauldam  can you tell me how you solve the problem?
