### ISSUE TITLE
Not working on API 16...

### ISSUE THREAD

**Issue by AdityaAnand1** [bravobit/FFmpeg-Android#7]
```
onFailure: reloc_library[1311]:  1421 cannot locate 'log2'...
CANNOT LINK EXECUTABLE
��
```

I tried this on an API 16 genymotion emulator and received the above output message in `onFailure()` (The command was `ffmpeg -version`). I can confirm that the exact same apk did work correctly on API 22 and 26.

**Comment by Brianvdb** [comment]
Thank you for the bug report. This issue is fixed in 19eb74fd39d43699ec88b689b98bab84bce71619

Use the latest version to fix the problem.
```gradle
dependencies {
    implementation 'nl.bravobit:android-ffmpeg:1.0.7'
}
```
