### ISSUE TITLE
Getting Glitches while overlaying one video on another !

### ISSUE THREAD

**Issue by kdblue** [bravobit/FFmpeg-Android#75]
Hello Dev ! Thanks for this library :)

Recently i am trying to overlaying one video on second video , second video shows in Circle . but unfortunate i am getting glitches on final video !

This command i am using to overlaying in cicle-

   command = "-i " + this.video1Path.getPath() + " -i " + this.video2Path.getPath() + " -filter_complex [1]trim=end_frame=1,geq=lum_expr='st(3,pow(X-(W/2),2)+pow(Y-(H/2),2));if(lte(ld(3)," + (this.mZoomLayout.getZoomedWidth()/2) + "*" + (this.mZoomLayout.getZoomedWidth()/2) + "),255,0)':128:128,format=gray,loop=-1:1,setpts=N/FRAME_RATE/TB[mask];[1][mask]alphamerge,format=rgba,lutrgb=a=if(gte(val\\,16)\\,val)[cutout];[0][cutout]overlay=" + this.mZoomLayout.getCircleX() + ":" + this.mZoomLayout.getCircleY() + ":enable='between(t,0," + this.videoTwoDuration + ") -c:v libx264 -crf 24 -preset ultrafast " + videoPath.getPath();

Any solution or suggestion for it ?

**Comment by Mirzaali-innovagictechnologies** [comment]
command = arrayOf<String>(
           "-i",
           SecondVideoUri.toString(),
           "-f",
           "lavfi",
           "-i",
           "movie=" + File(
               Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DCIM)
                   .toString() + "/" + "a.mov"
           ).absolutePath + ":loop=200,setpts=N/FRAME_RATE/TB",
           "-filter_complex",
           "[1:v][0:v]scale2ref[ua][b];[ua]setsar=1,format=yuva444p,colorchannelmixer=aa=0.7[u];[b][u]overlay=1:1:shortest=1 ",
           OpFilePath
       )

Use this command
