### ISSUE TITLE
Support APK fragmentation?

### ISSUE THREAD

**Issue by AdityaAnand1** [bravobit/FFmpeg-Android#8]
The library adds 30Mb to my app.

I was wondering if there was a way to exclude the ARM binary assets in a development productFlavor (since I mostly develop on emulators which are x86). I'm not sure how this works for a library.

Thoughts?

**Comment by Brianvdb** [comment]
Thank you for your question. I have updated the wiki and now you can read how to exclude binaries for specific architectures [https://github.com/bravobit/FFmpeg-Android/wiki/Reduce-APK-File-Size#exclude-architecture](https://github.com/bravobit/FFmpeg-Android/wiki/Reduce-APK-File-Size#exclude-architecture)
