### ISSUE TITLE
Question - Unrecognized option

### ISSUE THREAD

**Issue by MammouthQc** [bravobit/FFmpeg-Android#83]
I'm getting the error
`Unrecognized option 'filter_complex "[v]reverse[r];[v][r]concat"'.
Error splitting the argument list: Option not found`

When running the command
`-i /storage/emulated/0/DCIM/Camera/VID_20190101_112220.mp4 -filter_complex "[v]reverse[r];[v][r]concat" /storage/emulated/0/ParakeetVideos/VID_20190101_112220_EDIT_1.mp4`

           `String[] commands = new String[]
            {
                "-i",
                "/storage/emulated/0/DCIM/Camera/VID_20190101_112220.mp4",
                "-filter_complex \"[v]reverse[r];[v][r]concat\"",
                "/storage/emulated/0/ParakeetVideos/VID_20190101_112220_EDIT_1.mp4"
            };`

This command works on Windows 10 directly, so I'm fairly sure it's related to either this tool or permissions on Android?

I have those permissions in my AndroidManifest
`    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_INTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_INTERNAL_STORAGE" />`

**Comment by Brianvdb** [comment]
You are passing the commands the wrong way.

**Comment by MammouthQc** [comment]
Ok, could you please give me more information? I'm not sure what is the proper way, as I originally thought this was the proper way.

If it could help you awnser, here's the file where I call your tool: https://github.com/MammouthQc/ParakeetVideos/blob/master/app/src/main/java/business/sacdefromage/parakeetvideos/Edit.java

Thank you for your time 👍 !
@Brianvdb
