### ISSUE TITLE
Can support multi thread?

### ISSUE THREAD

**Issue by Blankeer** [bravobit/FFmpeg-Android#9]
I see the [code](https://github.com/bravobit/FFmpeg-Android/blob/master/android-ffmpeg/src/main/java/nl/bravobit/ffmpeg/FFmpeg.java#L116),only allowed to run single command at a time.
so,How to use multi command when multi thread?
thanks.

**Comment by adriandleon** [comment]
I am also interested on multi commands.

**Comment by function1983** [comment]
This works for me. It takes 3 steps:
1. Create FFmpegList.java:

```
    private static List<FFmpeg> instanceList;
    private final static int INSTANCE_COUNT = 2;
    public static List<FFmpeg> getInstanceList(final Context context) {
        if (instanceList == null) {
            //instanceList = new ArrayList<Pair<FFmpeg,FFcommandExecuteAsyncTask>>();
            instanceList = new ArrayList<>();
            for (int i = 0; i<INSTANCE_COUNT; i ++) {
                FFmpeg mFFmpeg = new FFmpeg(new FFbinaryContextProvider() {
                    @Override
                    public Context provide() {
                        return context;
                    }
                });
                instanceList.add(mFFmpeg);
            }
        }
        return instanceList;
    }
```

2. In FFmpeg.java you have to change:

`ffmpegExecuteAsyncTask.execute()`

to

`ffmpegExecuteAsyncTask.executeOnExecutor(AsyncTask.THREAD_POOL_EXECUTOR)`

This will make sure the asynctasks run in parallel (which I think what you want)

3. Create MyService.java:
```
FFmpeg ffmpeg = FFmpegList.getInstanceList(getApplicationContext()).get(0);
try {
ffmpeg.execute(cmd, new ExecuteBinaryResponseHandler() {}...
}
```

**Comment by Brianvdb** [comment]
@function1983 Thanks for that code.

Multithreading has now been added for FFmpeg & FFprobe commands. 

```gradle
dependencies {
    implementation 'nl.bravobit:android-ffmpeg:1.1.2'
}
````
