### ISSUE TITLE
Invalid data found when processing input

### ISSUE THREAD

**Issue by Kadanza** [bravobit/FFmpeg-Android#92]
I have problem with FFprobe

commands = 
0 = "-v"
1 = "error"
2 = "-show_entries"
3 = "format=duration"
4 = "-of"
5 = "default=noprint_wrappers=1:nokey=1"
6 = "/storage/9C33-6BBD/Video/S01E06_x264_001.mp4"

fFprobe.execute(cmd)

when I have error
`
[mov,mp4,m4a,3gp,3g2,mj2 @ 0xaca74a10] moov atom not found`
 `S01E06_x264_001.mp4: Invalid data found when processing input`

**Comment by Brianvdb** [comment]
Could be a corrupt file, or a FFprobe issue. Not related to this library.
